### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by fred-wang** [MathML/MathMLinHTML5#1]
We need something that allows easy reuse, especially for browser vendors or W3C WG. Hence a W3C license seems the most appropriate:

http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document
http://www.w3.org/Consortium/Legal/2015/doc-license.html
http://www.w3.org/2002/09/wbs/40318/html5-license-poll/results

**Comment by kohlhase** [comment]
I agree in principle, but the concrete license states ownership of W3C, so we cannot use it unchanged .
Probably CC-by is more suitable for our purposes.

**Comment by fred-wang** [comment]
> I agree in principle, but the concrete license states ownership of W3C, so we cannot use it unchanged .

Apparently this was changed in 2002:
http://www.w3.org/Consortium/Legal/2002/copyright-documents-20021231

"This formulation of W3C's notice and license became active on December 31 2002. This version removes the copyright ownership notice such that this license can be used with materials other than those owned by the W3C, moves information on style sheets, DTDs, and schemas to the Copyright FAQ, reflects that ERCIM is now a host of the W3C, includes references to this specific dated version of the license, and removes the ambiguous grant of "use". See the older formulation for the policy prior to this date. Please see our Copyright FAQ for common questions about using materials from our site, such as the translating or annotating specifications. "

> Probably CC-by is more suitable for our purposes. 

I plan to ask feedback to browser developers, so I can also ask them which license they prefer.
