### ISSUE TITLE
clarify spacing around mfrac

### ISSUE THREAD

**Issue by fred-wang** [MathML/MathMLinHTML5#30]
Currently, the implementation note gives 0 spacing around fractions unless the numerator is an embellished operator (in that case the lspace/rspace values are used).

WebKit uses 0 spacing and at the moment embellished operator spacing is not currently implemented.

Gecko always sets a minimum of 1px spacing around fractions (and adds the embellished op spacing to this 1px if necessary). This allows for example to distinguish \frac{a}{b}\frac{c}{d} VS \frac{ac}{bd}.

At the moment this uncertainty makes difficult to write frac tests that work on all browsers.

@khaledhosny: what do you think about it? Should we add this minimum spacing?

**Comment by khaledhosny** [comment]
There should be spacing around fractions somehow, else things like `\frac{1}{2}\frac{3}{4}` or `-\frac{1}{2}` will look odd. I came across this while working on libmathview, and ended up adding a thinspace around fractions (see https://github.com/khaledhosny/libmathview/commit/ba7cd2076487ea947c15dd05ce9c96ec445f0bbd for details).

**Comment by fred-wang** [comment]
@khaledhosny  Thanks, I'm not sure from the diff, but I guess the space is added to the operator spacing (in case mfrac is itself an embellished operator).

I think a more general discussion on spacing is needed since as indicated in the comment the MathML rules are different from TeX. For now, the implementation note only says that only operator lspace/rspace and italic correction adds spacing in row-like elements: http://www.mathml-association.org/MathMLinHTML5/S3.html#SS3.SSS1 . If you have better rules to propose that we can formalize, that would be great.

**Comment by khaledhosny** [comment]
I think my conclusion back then (I’m a bit fuzzy in details as well) was that if a fraction is preceded by something that is not an operator then add thin space before it, and the same on the other side. This avoid adding spaces when fractions is at the start and/or end of the equation, or to add double spacing around operators.

**Comment by fred-wang** [comment]
@khaledhosny OK, this is what I read from the diff. However, I don't know what happens when the numerator is itself an embellished operator.

**Comment by khaledhosny** [comment]
My MathML is rusty, can you give an example of such fraction?

**Comment by fred-wang** [comment]
I don't have any example with concrete mathematical meaning but for example

    <math><mn>1</mn><mfrac><mo>+</mo><mn>2</mn></mfrac><mn>3</mn></math>

The spec says that + is treated as index and spacing added around the whole fraction.

Anyway, until the whole spacing rule is clarified, I guess I'll just mention Gecko's simple rule: add 1px around all the fractions. That way that will fix the spacing issue in WebKit and alllow to write more reliable rendering tests.

**Comment by khaledhosny** [comment]
TeX does not added any extra spacing because of such operator and I think that is logical, the content of the fraction shouldn’t affect how the fraction itself is spaced. Furthermore an operator on itself does not get any extra spacing in TeX at all, since the spacing rules only kick in when the symbol is followed by another one.

**Comment by fred-wang** [comment]
> TeX does not added any extra spacing because of such operator and I think that is logical, the content of the fraction shouldn’t affect how the fraction itself is spaced. Furthermore an operator on itself does not get any extra spacing in TeX at all, since the spacing rules only kick in when the symbol is followed by another one.

I know this but I'm not sure I follow the connection of this latest comment with the previous discussion...  I was more interested about how you handle the spacing in libmathview in order to solve that fraction issue. So IIUC, libmathview does not comply with the MathML recommendation regarding embellished operator here and instead tries to emulate what TeX would do by assigning the Inner type to fractions. As I said above, I'll probably just say 1px should be added for now.

For future references:
* TeX spacing is mentioned here: http://www.mathml-association.org/MathMLinHTML5/S2.html#SS2.SSS2
* Gecko's non-standard rules: http://hg.mozilla.org/mozilla-central/file/tip/layout/mathml/nsMathMLContainerFrame.cpp#l1058
